### ISSUE TITLE
Doesn't work with obsidian-modules

### ISSUE THREAD

**Issue by stef-rausch** [HananoshikaYomaru/obsidian-run#14] opened 2023-10-05 11:46 UTC
See https://github.com/HananoshikaYomaru/obsidian-run/issues/9 -- the issue persists.

**Comment by HananoshikaYomaru** [comment] 2023-10-05 16:06
Interesting. Can you give me a code to reproduce. I cannot use your code because of the require statement

**Comment by stef-rausch** [comment] 2023-10-05 17:58
I use the `Modules` plugin: https://github.com/polyipseity/obsidian-modules -- obsidian://show-plugin?id=modules.

There may be something in the codebase that gives you an indication.

**Comment by HananoshikaYomaru** [comment] 2023-10-05 19:50
sorry, I cannot do this because because I cannot fix my plugin just to integrate with another plugin. As long as normal async function work, I will treat the feature as "complete".

**Comment by HananoshikaYomaru** [comment] 2023-10-05 22:06
For user defined scripts, I have already support templater. You can check the readme.

**Comment by stef-rausch** [comment] 2023-10-05 23:08
Well, it is not about "fixing" your plugin. It is about complementing as much as possible.

You are already offering the integration with `Dataview` -- I have not checked how complete the integration is -- and partially with `Templater`. Why partially? See below:

~~~
%% run start

```js
return await tp.file.include("[[test.vim]]")
``` 

%%
Loading...
%% run end %%
~~~

I am trying to include a pure text note... as soon as an `await` call is necessary, your plugin "hangs". Please, don't get me wrong, I am only trying to show you the "rough" edges.

**Comment by HananoshikaYomaru** [comment] 2023-10-06 03:49
OK. I think I understand why. Sorry I didn't elaborate clearly in the doc. That is not the problem of my plugin, that is the problem of templater. because templater `tp` which is the internal `current_functions_object` is undefined unless run once. Therefore you need to set the templater at least one startup template. 

see more on: https://forum.obsidian.md/t/templater-api/59117/6?u=yomaru

This issue cannot fixed by me because I have look at this already before I added the templater integration. The initialization of `current_functions_object` is private and other plugins has no way to call it. 

I will update the doc. 

https://github.com/HananoshikaYomaru/obsidian-run/assets/43137033/d0bc225d-da19-4bf3-bece-a601ba6480ab

**Comment by HananoshikaYomaru** [comment] 2023-10-06 03:54
I updated the doc

<img width="1032" alt="CleanShot 2023-10-05 at 20 53 46@2x" src="https://github.com/HananoshikaYomaru/obsidian-run/assets/43137033/77da4ae5-877b-4f35-ac31-f3e17efcff6c">

**Comment by HananoshikaYomaru** [comment] 2023-10-06 04:21
One thing I can assure that this plugin is **Extremely** complete. The reason why it is extremely complete is because how I write the code, I delegate the calculation to dataview and templater itself. If operation fails, it is not because of this plugin, it is because of the dataview and templater. The issues need to be opened in dataview and templater. 

Obsidian Run at its core is a javascript running engine. As long as it is javascript is valid, it will be executed valid. There is no magic. And therefore it is robust.

**Closed as completed** 2023-10-06 04:22 UTC
Labels: bug, invalid, wontfix

**Comment by stef-rausch** [comment] 2023-10-06 17:22
Noted.

I have `Templater` installed and active on all my devices, including one startup template, one folder template and two user scripts, which I use daily. One of my user scripts even checks and waits for `Templater` to be up and running before proceeding.

So all preconditions are met, but `Run` does not allow me to use `await`.

I will take some distance and maybe after a few days, I have a light bulb moment.

Keep up the good work!

**Comment by HananoshikaYomaru** [comment] 2023-10-06 18:11
yeah. If you really need help, just feel free to arrange a call with me. 

https://cal.com/manlung
